site_name: ckanext-openapi
site_url: https://mjanez.github.io/ckanext-openapi/   # Local: mkdocs serve -a 127.0.0.1:8088
site_description: >-
  Integrating OpenAPI documentation with CKAN instances.
repo_name: mjanez/ckanext-openapi
repo_url: https://github.com/mjanez/ckanext-openapi

nav:
  - Home: index.md
  - Getting Started: v1/getting-started.md
  - Development:
    - Translations: v1/dev-translations.md
    - Plugin docs with MKDocs: v1/dev-mkdocs.md
    - Update ChangeLog: v1/dev-changelog.md
  - Configuration reference: v1/configuration.md
  - Running the Tests: v1/tests.md
  - CHANGELOG: changelog.md

theme:
  name: material
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/toggle-switch-off
        name: Switch to light mode

  logo: _assets/logo.png
  favicon: _assets/ckan.ico
  features:
    - navigation.expand
    - navigation.footer
    - navigation.instant
    - navigation.instant.progress
    - search.suggest
    - search.highlight
    - toc.integrate
    - content.code.copy
    - content.footnote.tooltips
    - content.tooltips

plugins:
  - search

markdown_extensions:
  - toc:
      permalink: true
  - admonition
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.details
  - codehilite
  - footnotes
  - abbr
  - attr_list
  - md_in_html

extra_css:
  - _css/extra.css

exclude_docs: |
    !/doc/*
    !/README.md
